# Generated by Django 4.2.8 on 2024-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_nome_counties_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.CharField(default='Sudeste', max_length=100),
            preserve_default=False,
        ),
    ]
