# Generated by Django 4.2.8 on 2024-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_state_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='uf',
            field=models.CharField(default='SP', max_length=2),
            preserve_default=False,
        ),
    ]
