# Generated by Django 4.2.8 on 2024-05-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_state_uf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counties',
            new_name='County',
        ),
    ]
